// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace teste.DATA.Models;

public partial class Cliente
{
    [Key]
    public int IdCliente { get; set; }

    [Required]
    [StringLength(50)]
    public string Nome { get; set; }

    [Required]
    [StringLength(50)]
    public string Endereço { get; set; }

    [Required]
    [StringLength(20)]
    public string Telefone { get; set; }

    [InverseProperty("IdClienteNavigation")]
    public virtual ICollection<LivroCliente> LivroCliente { get; set; } = new List<LivroCliente>();
}