// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace teste.DATA.Models;

public partial class Livro
{
    [Key]
    public int IdLivro { get; set; }

    [Required]
    [StringLength(50)]
    public string Titulo { get; set; }

    [Required]
    [StringLength(50)]
    public string Autor { get; set; }

    [Required]
    [StringLength(50)]
    public string Editora { get; set; }

    [InverseProperty("IdLivroNavigation")]
    public virtual ICollection<LivroCliente> LivroCliente { get; set; } = new List<LivroCliente>();
}