// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace teste.DATA.Models;

[Table("Livro_Cliente")]
public partial class LivroCliente
{
    [Key]
    [Column("IdEmprestimo")]
    public int IdEmprestimo { get; set; }

    public int IdLivro { get; set; }

    public int IdCliente { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataEmprestimo { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime DataDevolucao { get; set; }

    public bool DataEntregue { get; set; }

    [ForeignKey("IdCliente")]
    [InverseProperty("LivroCliente")]
    public virtual Cliente IdClienteNavigation { get; set; }

    [ForeignKey("IdLivro")]
    [InverseProperty("LivroCliente")]
    public virtual Livro IdLivroNavigation { get; set; }
}